apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: emqx-tls 
spec:
  # secretName doesn't have to match the certificate name, but it may as well, for simplicity!
  secretName: emqx-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - "hass-mqtt.animaniacs.farh.net"