apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
  name: emqx
spec:
  image: emqx:5
  imagePullPolicy: Always
  config:
    data: |
      listeners.ssl.default {
        bind = "0.0.0.0:8883"
        ssl_options {
        #  cacertfile = "/mounted/cert/ca.crt"
          certfile = "/mounted/cert/tls.crt"
          keyfile = "/mounted/cert/tls.key"
          gc_after_handshake = true
          handshake_timeout = 5s
        }
      }
  coreTemplate:
    spec:
      volumeClaimTemplates:
        storageClassName: ceph-block
        resources:
          requests:
            storage: 1Gi
        accessModes:
          - ReadWriteOnce
      replicas: 3
      extraVolumes:
        - name: emqx-tls
          secret:
            secretName: emqx-tls
      extraVolumeMounts:
        - name: emqx-tls
          mountPath: /mounted/cert
  #replicantTemplate:
  #  spec:
  #    extraVolumes:
  #      - name: emqx-tls
  #        secret:
  #          secretName: emqx-tls
  #    extraVolumeMounts:
  #      - name: emqx-tls
  #        mountPath: /mounted/cert
  listenersServiceTemplate:
    metadata:
      annotations:
        service.cilium.io/forwarding-mode: dsr
        external-dns.alpha.kubernetes.io/hostname: "hass-mqtt.animaniacs.farh.net"
    spec:
      type: LoadBalancer
      externalTrafficPolicy: Local
      