apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password
  database: hass
  username: hass
  passwordSecretKeyRef:
    name: mariadb
    key: hass
  storage:
    size: 8Gi
    storageClassName: ceph-block
    resizeInUseVolumes: true
    waitForVolumeResize: true
    volumeClaimTemplate:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 8Gi
      storageClassName: ceph-block
  replicas: 3
  service:
    type: LoadBalancer
    externalTrafficPolicy: Local
    metadata:
      annotations:
        service.cilium.io/forwarding-mode: dsr
        external-dns.alpha.kubernetes.io/hostname: "db.hass.farh.net"
  primaryService:
    type: LoadBalancer
    externalTrafficPolicy: Local
    metadata:
      annotations:
        service.cilium.io/forwarding-mode: dsr
  secondaryService:
    type: LoadBalancer
    externalTrafficPolicy: Local
    metadata:
      annotations:
        service.cilium.io/forwarding-mode: dsr
  metrics:
    enabled: false
  resources:
    requests:
      cpu: 250m
      memory: 4Gi
    limits:
      memory: 8Gi
  galera:
    enabled: true
  myCnf: |
    [mariadb]
    innodb_buffer_pool_size=1024M